// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duhscmzvkqeudnmllggg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1aHNjbXp2a3FldWRubWxsZ2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDAxOTEsImV4cCI6MjA2NzQxNjE5MX0.sbL2BdVP5UnM1M5eEGemF3OLkpwemDWttiH_e_ciDhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});